### ISSUE TITLE
[BUG] Minecraft crashes on startup with OkZoomer

### ISSUE THREAD

**Issue by Delta-official** [joaoh1/OkZoomer#34]
![Знімок екрана  о 10 14 31](https://user-images.githubusercontent.com/64544951/126891989-c0da1300-b3ab-417e-9ce0-252a29718850.png)

Platform: MacOS Mojave

Log:
```console
[10:08:49] [main/INFO]: Loading for game Minecraft 1.17.1
[10:08:49] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b44633d, also found 0.3.0+a02b446318
 - Conflicting versions found for fabric-screen-api-v1: used 1.0.4+155f865c18, also found 1.0.4+198a96213d
[10:08:49] [main/INFO]: [FabricLoader] Loading 60 mods:
	- appleskin@mc1.17-2.1.0
	- cloth-basic-math@0.5.1
	- cloth-config2@5.0.34
	- fabric@0.37.1+1.17
	- fabric-api-base@0.3.0+a02b44633d
	- fabric-api-lookup-api-v1@1.2.0+2b5c62d018
	- fabric-biome-api-v1@3.1.11+c345aea818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+a02b446318
	- fabric-content-registries-v0@0.2.2+a02b446318
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.1.0+a02b446318
	- fabric-events-interaction-v0@0.4.9+a722d8c018
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+6cefd57718
	- fabric-item-api-v1@1.2.4+a02b446318
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+a02b446318
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-lifecycle-events-v1@1.4.4+a02b446318
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.12+6cefd57718
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+b7ab612118
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+5f02c96918
	- fabric-renderer-indigo@0.4.8+a02b446318
	- fabric-renderer-registries-v1@3.2.0+a02b446318
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446318
	- fabric-rendering-fluids-v1@0.1.13+a02b446318
	- fabric-rendering-v0@1.1.2+92519afa18
	- fabric-rendering-v1@1.6.0+a02b446318
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+155f865c18
	- fabric-screen-handler-api-v1@1.1.8+a02b446318
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.1.4+a02b446318
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
	- fabric-transfer-api-v1@1.0.0+3fe3c3f518
	- fabricloader@0.11.6
	- fiber@0.23.0-2
	- java@16
	- lambdynlights@2.0.1+1.17
	- minecraft@1.17.1
	- modmenu@2.0.3
	- okzoomer@4.0.1+1.16.2
	- org_aperlambda_lambdajcommon@1.8.1
	- pling@1.4.0
	- spruceui@3.2.0+1.17
	- torohealth@1.17.1-fabric-9
	- waila@1.9.22
[10:08:49] [main/WARN]: Mod `appleskin` (mc1.17-2.1.0) does not respect SemVer - comparison support is limited.
[10:08:49] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/Users/prezentlilia/Library/Application%20Support/minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[10:08:50] [main/INFO]: Compatibility level set to JAVA_16
[10:08:51] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[10:09:03] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:09:06] [Render thread/INFO]: Setting user: Epsilon_ish
[10:09:06] [Render thread/INFO]: Discovered plugin waila:core provided by waila at mcp.mobius.waila.addons.core.PluginCore
[10:09:06] [Render thread/INFO]: Discovered plugin waila:vanilla provided by waila at mcp.mobius.waila.addons.minecraft.PluginMinecraft
[10:09:06] [Render thread/INFO]: Registering plugin at mcp.mobius.waila.addons.core.PluginCore
[10:09:06] [Render thread/INFO]: Registering plugin at mcp.mobius.waila.addons.minecraft.PluginMinecraft
[10:09:06] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zbh000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[10:09:07] [Render thread/INFO]: [LambDynLights] Initializing LambDynamicLights...
[10:09:07] [Render thread/INFO]: [LambDynLights] Configuration loaded.
[10:09:07] [Render thread/ERROR]: Error enabling the Mod Menu config button for Hwyla
java.lang.ClassNotFoundException: io.github.prospector.modmenu.ModMenu
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175) ~[fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at mcp.mobius.waila.WailaClient.enableModMenuConfig(WailaClient.java:37) ~[Hwyla-fabric-1.16.2-1.9.23-79.jar:?]
	at mcp.mobius.waila.WailaClient.onInitializeClient(WailaClient.java:32) ~[Hwyla-fabric-1.16.2-1.9.23-79.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34) [fabric-loader-0.11.6.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:457) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:179) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
... (48 lines left)
Collapse
latest.log
13 KB
anatevka
 — Today at 10:24
seems to be Lithium
nvm
Platy VCB
 — Today at 10:28
that would be incredibly concerning
anatevka
 — Today at 10:28
yeah I'm just wrong
Player
 — Today at 10:49
that's a rather interesting one, either something ships a broken class, hacks a low level transformer into fabric loader or mixin has a bug that emits invalid code
unfortunately it doesn't even tell what the affected class it, let alone what was been touching it (i just fixed the former in a pending pr)
you can really only investigate this further by removing mods (remove half+their dependent mods, then if that works add half back / remove another half, ...)
Darkuss
 — Today at 10:51
so, is it time to compile fabric from a pr or can it be fixed on this version?
Player
 — Today at 10:52
since you only have a few mods it'd be best to bisect mods first imo
and we're quite far from a fix, very unclear what's wrong
Darkuss
 — Today at 10:54
okzoomer was the culprit
time to possibly open an issue
﻿
[10:08:49] [main/INFO]: Loading for game Minecraft 1.17.1
[10:08:49] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b44633d, also found 0.3.0+a02b446318
 - Conflicting versions found for fabric-screen-api-v1: used 1.0.4+155f865c18, also found 1.0.4+198a96213d
[10:08:49] [main/INFO]: [FabricLoader] Loading 60 mods:
	- appleskin@mc1.17-2.1.0
	- cloth-basic-math@0.5.1
	- cloth-config2@5.0.34
	- fabric@0.37.1+1.17
	- fabric-api-base@0.3.0+a02b44633d
	- fabric-api-lookup-api-v1@1.2.0+2b5c62d018
	- fabric-biome-api-v1@3.1.11+c345aea818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+a02b446318
	- fabric-content-registries-v0@0.2.2+a02b446318
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.1.0+a02b446318
	- fabric-events-interaction-v0@0.4.9+a722d8c018
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+6cefd57718
	- fabric-item-api-v1@1.2.4+a02b446318
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+a02b446318
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-lifecycle-events-v1@1.4.4+a02b446318
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.12+6cefd57718
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+b7ab612118
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+5f02c96918
	- fabric-renderer-indigo@0.4.8+a02b446318
	- fabric-renderer-registries-v1@3.2.0+a02b446318
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446318
	- fabric-rendering-fluids-v1@0.1.13+a02b446318
	- fabric-rendering-v0@1.1.2+92519afa18
	- fabric-rendering-v1@1.6.0+a02b446318
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+155f865c18
	- fabric-screen-handler-api-v1@1.1.8+a02b446318
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.1.4+a02b446318
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
	- fabric-transfer-api-v1@1.0.0+3fe3c3f518
	- fabricloader@0.11.6
	- fiber@0.23.0-2
	- java@16
	- lambdynlights@2.0.1+1.17
	- minecraft@1.17.1
	- modmenu@2.0.3
	- okzoomer@4.0.1+1.16.2
	- org_aperlambda_lambdajcommon@1.8.1
	- pling@1.4.0
	- spruceui@3.2.0+1.17
	- torohealth@1.17.1-fabric-9
	- waila@1.9.22
[10:08:49] [main/WARN]: Mod `appleskin` (mc1.17-2.1.0) does not respect SemVer - comparison support is limited.
[10:08:49] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/Users/prezentlilia/Library/Application%20Support/minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[10:08:50] [main/INFO]: Compatibility level set to JAVA_16
[10:08:51] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[10:09:03] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:09:06] [Render thread/INFO]: Setting user: Epsilon_ish
[10:09:06] [Render thread/INFO]: Discovered plugin waila:core provided by waila at mcp.mobius.waila.addons.core.PluginCore
[10:09:06] [Render thread/INFO]: Discovered plugin waila:vanilla provided by waila at mcp.mobius.waila.addons.minecraft.PluginMinecraft
[10:09:06] [Render thread/INFO]: Registering plugin at mcp.mobius.waila.addons.core.PluginCore
[10:09:06] [Render thread/INFO]: Registering plugin at mcp.mobius.waila.addons.minecraft.PluginMinecraft
[10:09:06] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zbh000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[10:09:07] [Render thread/INFO]: [LambDynLights] Initializing LambDynamicLights...
[10:09:07] [Render thread/INFO]: [LambDynLights] Configuration loaded.
[10:09:07] [Render thread/ERROR]: Error enabling the Mod Menu config button for Hwyla
java.lang.ClassNotFoundException: io.github.prospector.modmenu.ModMenu
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175) ~[fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at mcp.mobius.waila.WailaClient.enableModMenuConfig(WailaClient.java:37) ~[Hwyla-fabric-1.16.2-1.9.23-79.jar:?]
	at mcp.mobius.waila.WailaClient.onInitializeClient(WailaClient.java:32) ~[Hwyla-fabric-1.16.2-1.9.23-79.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34) [fabric-loader-0.11.6.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:457) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:179) [intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[10:09:07] [Render thread/WARN]: WARNING! Mod torohealth is only using deprecated 'modmenu:clientsideOnly' custom value! This is no longer needed and will be removed in 1.18 snapshots.
[10:09:07] [Render thread/WARN]: WARNING! Mod fiber is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[10:09:07] [Render thread/WARN]: WARNING! Mod cloth-basic-math is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.
[10:09:07] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[10:09:08] [Render thread/INFO]: Backend library: LWJGL version 3.2.1 build 12
[10:09:09] [Render thread/INFO]: [STDERR]: org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 175: Expected D, but found .
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:292)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.util.Locals.generateLocalVariableTable(Locals.java:394)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.util.Locals.getGeneratedLocalVariableTable(Locals.java:363)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.util.Locals.getLocalVariableAt(Locals.java:317)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.util.Locals.getLocalVariableAt(Locals.java:287)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.util.Locals.getLocalsAt(Locals.java:250)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator$Context.initLocals(LocalVariableDiscriminator.java:136)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.modify.LocalVariableDiscriminator$Context.<init>(LocalVariableDiscriminator.java:130)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector$Context.<init>(ModifyVariableInjector.java:69)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:146)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:492)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:179)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
[10:09:09] [Render thread/INFO]: [STDERR]: Caused by: org.objectweb.asm.tree.analysis.AnalyzerException: Expected D, but found .
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.objectweb.asm.tree.analysis.BasicVerifier.copyOperation(BasicVerifier.java:103)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.objectweb.asm.tree.analysis.BasicVerifier.copyOperation(BasicVerifier.java:43)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:326)
[10:09:09] [Render thread/INFO]: [STDERR]: 	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:188)
[10:09:09] [Render thread/INFO]: [STDERR]: 	... 33 more
````

**Comment by EnnuiL** [comment]
You are using a version of Ok Zoomer meant for Minecraft 1.16 on Minecraft 1.17.1, which is not compatible. Please use Ok Zoomer 5.0.0-beta.2 instead
In order to avoid issues like that, if you are downloading from CurseForge, never use the Download button on the top, it's not reliable and may download the wrong version;
![image](https://user-images.githubusercontent.com/85590273/124335220-07495a80-db70-11eb-9d60-ad84e1eef481.png)
