### ISSUE TITLE
Command-related crashes with Ok Zoomer

### ISSUE THREAD

**Issue by itsMarkiS** [joaoh1/OkZoomer#67]
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.LinkageError: loader constraint violation: when resolving field "BUILT_IN_EXCEPTIONS" of type com.mojang.brigadier.exceptions.BuiltInExceptionProvider, the class loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @ebaa6cb of the current class, net.minecraft.class_155, and the class loader 'app' for the field's defining class, com.mojang.brigadier.exceptions.CommandSyntaxException, have different Class objects for type com.mojang.brigadier.exceptions.BuiltInExceptionProvider (net.minecraft.class_155 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @ebaa6cb, parent loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @758705fa; com.mojang.brigadier.exceptions.CommandSyntaxException is in unnamed module of loader 'app')
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.LinkageError: loader constraint violation: when resolving field "BUILT_IN_EXCEPTIONS" of type com.mojang.brigadier.exceptions.BuiltInExceptionProvider, the class loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @ebaa6cb of the current class, net.minecraft.class_155, and the class loader 'app' for the field's defining class, com.mojang.brigadier.exceptions.CommandSyntaxException, have different Class objects for type com.mojang.brigadier.exceptions.BuiltInExceptionProvider (net.minecraft.class_155 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @ebaa6cb, parent loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @758705fa; com.mojang.brigadier.exceptions.CommandSyntaxException is in unnamed module of loader 'app')
	at net.minecraft.class_155.<clinit>(class_155.java:214)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	... 2 more

**Comment by vaporvee** [comment]
Same issue i use version `5.0.0-beta.6+1.18.2` i think you mean it crashes on minecraft startup

**Comment by EnnuiL** [comment]
Hello! Could you try and crash the game again and then also annex the `latest.log` file from `.minecraft/logs/`? I'm suspecting that this is a mod conflict; That, or perhaps a mod load order issue?

**Comment by itsMarkiS** [comment]
discovered that it is because of the way it uses both fabric and quilt api

**Comment by nertosey** [comment]
good afternoon, for some reason this mod does not work for me

**Comment by vaporvee** [comment]
Oh man please learn how to use github

**Comment by EnnuiL** [comment]
Stale issue; we (unfortunately) came back to Fabric API anyway
