### ISSUE TITLE
Crash on start with Fabric Loader v0.14.0 (okzoomer-5.0.0-beta.6+1.18.2)

### ISSUE THREAD

**Issue by Wahngrok** [joaoh1/OkZoomer#74]
This does not happen with Fabric Loader v0.13.3

---

[main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'quilt_command'!
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:156) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:69) [fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'quilt_command'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:154) ~[fabric-loader-0.14.0.jar:?]
	... 10 more
Caused by: java.lang.ExceptionInInitializerError
	at org.quiltmc.qsl.command.impl.PreLaunchInitializer.onPreLaunch(PreLaunchInitializer.java:33) ~[quilt_command-1.0.0+1.18.2-SNAPSHOT-5739c0c319a3f50b.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:154) ~[fabric-loader-0.14.0.jar:?]
	... 10 more
Caused by: java.lang.RuntimeException: Failed to load Classloader fields
	at org.quiltmc.qsl.base.impl.PreLaunchHacks.<clinit>(PreLaunchHacks.java:49) ~[quilt_base-1.0.0+1.18.2-SNAPSHOT-95e80be7208cdff7.jar:?]
	at org.quiltmc.qsl.command.impl.PreLaunchInitializer.onPreLaunch(PreLaunchInitializer.java:33) ~[quilt_command-1.0.0+1.18.2-SNAPSHOT-5739c0c319a3f50b.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:154) ~[fabric-loader-0.14.0.jar:?]
	... 10 more
Caused by: java.lang.NoSuchMethodException: net.fabricmc.loader.impl.launch.knot.KnotClassLoader.addURL(java.net.URL)
	at java.lang.Class.getMethod(Class.java:2227) ~[?:?]
	at org.quiltmc.qsl.base.impl.PreLaunchHacks.<clinit>(PreLaunchHacks.java:46) ~[quilt_base-1.0.0+1.18.2-SNAPSHOT-95e80be7208cdff7.jar:?]
	at org.quiltmc.qsl.command.impl.PreLaunchInitializer.onPreLaunch(PreLaunchInitializer.java:33) ~[quilt_command-1.0.0+1.18.2-SNAPSHOT-5739c0c319a3f50b.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:154) ~[fabric-loader-0.14.0.jar:?]
	... 10 more
Process exited with code 1.

**Comment by EnnuiL** [comment]
With the full migration to the Quilt toolchain (and therefore, the Quilt Loader) and the possible culprit being removed on the Quiltified version of QSL, this issue shouldn't happen anymore with 5.0.0-beta.7, although this means that the Fabric Loader isn't supported anymore
