### ISSUE TITLE
Loading worlds in singleplayer and in some servers doesnt works 

### ISSUE THREAD

**Issue by itsMarkiS** [joaoh1/OkZoomer#77]
when using the latest fabric version (okzoomer-5.0.0-beta.4+1.18.2) or even beta5, we cant load worlds or some servers cause of the way it is built with both quilt and fabric API... i cant use the mod anymore cause of it... ive also tried to use Quilt instead but i cant use all of my mods in quilt, so i was thinking about, if possible, making a rebuilt version of 5.0.0-BETA or any other, for 1.18.2 but with only fabric api on it so it can work easily

> yes the error is from OkZoomer (also when using Inspecio or any other mod with both Quilt and Fabric API together instead of only a specific one)

java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/resource/loader/FabricResource
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.client.MinecraftClient.createSaveLoader(MinecraftClient:2124) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1972) ~[?:?]
	at net.minecraft.client.MinecraftClient.createWorld(MinecraftClient:1941) ~[?:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.createLevel(CreateWorldScreen:286) ~[?:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.method_19922(CreateWorldScreen:230) ~[?:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:40) ~[?:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16) ~[?:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:121) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:537) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:94) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:492) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:165) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:118) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:165) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem:225) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1150) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/resource/loader/FabricResource
	at net.fabricmc.fabric.impl.loot.LootUtil.determineSource(LootUtil.java:41) ~[fabric-loot-api-v2-1.0.0+e747827960-c04a6148053b4bde.jar:?]
	at net.minecraft.loot.LootManager.md64698e$lambda$apply$0$0(LootManager:564) ~[?:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.loot.LootManager.handler$bcl000$apply(LootManager:555) ~[?:?]
	at net.minecraft.loot.LootManager.apply(LootManager:59) ~[?:?]
	at net.minecraft.loot.LootManager.apply(LootManager:17) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader:13) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:69) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:198) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:163) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:176) ~[?:?]
	at net.minecraft.client.MinecraftClient.createSaveLoader(MinecraftClient:2123) ~[?:?]
	... 24 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.resource.loader.FabricResource
	at net.fabricmc.fabric.impl.loot.LootUtil.determineSource(LootUtil.java:41) ~[fabric-loot-api-v2-1.0.0+e747827960-c04a6148053b4bde.jar:?]
	at net.minecraft.loot.LootManager.md64698e$lambda$apply$0$0(LootManager:564) ~[?:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.loot.LootManager.handler$bcl000$apply(LootManager:555) ~[?:?]
	at net.minecraft.loot.LootManager.apply(LootManager:59) ~[?:?]
	at net.minecraft.loot.LootManager.apply(LootManager:17) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader:13) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:69) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:198) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:163) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:176) ~[?:?]
	at net.minecraft.client.MinecraftClient.createSaveLoader(MinecraftClient:2123) ~[?:?]
	... 24 more

**Comment by GribanovIvan** [comment]
beta.3 works fine on 1.18.2 anyway

**Comment by GribanovIvan** [comment]
[nvm](https://github.com/EnnuiL/OkZoomer/issues/78)

**Comment by EnnuiL** [comment]
This issue is caused by the bundled Quilted Fabric API (which was temporarily based on the Fabric Loader back then) being ancient in comparison to the latest Fabric API, with the lack of a pillar required for Loot API v2 to work being the specific cause. The latest Quilted Fabric API properly supports new APIs such as the Loot API v2 and since 5.0.0-beta.7, Ok Zoomer doesn't bundle it anymore, future-proofing against those kinds of issues;

I do understand your situation, although about maintaining a pure Fabric version of the mod, even ignoring the community issues that led to the switch, it's already being hard to juggle between multiple mod projects; I don't wish to stretch myself to work on two platforms whose divergences only gets bigger while Ok Zoomer increases its usage of Quilt features; Instead of using a version of Ok Zoomer that only keeps getting more broken, I recommend using [an alternative zoom mod](https://lambdaurora.dev/optifine_alternatives/#zoom) for now
