### ISSUE TITLE
Crash report?

### ISSUE THREAD

**Issue by ShrodeFling** [joaoh1/OkZoomer#88]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, version 0.14.0 or later.
Unmet dependency listing:
	 - Mod 'Ok Zoomer' (okzoomer) 4.0.1+1.16.2 requires version 0.14.0 or later of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

i tried loader version 
0.14.0
0.14.5
0.14.10
all in the 1.16.5 version of minecraft
none of them worked

**Comment by stantios** [comment]
This issue is a bit old but if you can, do you think you can post the full log to mclo.gs and paste the link here?
